name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

# Cancel superseded PR runs when the PR is updated
concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node 20
        uses: actions/setup-node@v5
        with:
          node-version: latest

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint
        continue-on-error: false

      - name: Test
        run: bun run test

      - name: Build
        run: bun run build